# Generated by Django 5.2.11 on 2026-03-18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomePlusOnboardingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('invite_token', models.UUIDField(blank=True, null=True, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_holder', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_ifsc', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=255, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=20, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=30, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=20, null=True)),
                ('pan_document_url', models.TextField(blank=True, null=True)),
                ('gst_document_url', models.TextField(blank=True, null=True)),
                ('aadhar_document_url', models.TextField(blank=True, null=True)),
                ('current_step', models.PositiveSmallIntegerField(default=1)),
                ('step1_completed', models.BooleanField(default=False)),
                ('step2_completed', models.BooleanField(default=False)),
                ('step3_completed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('invited', 'Invited'), ('in_progress', 'In Progress'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='requested', max_length=30)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('invite_sent_at', models.DateTimeField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomeplus_onboarding_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IncomePlus Onboarding Request',
                'verbose_name_plural': 'IncomePlus Onboarding Requests',
                'db_table': 'identity_incomeplus_onboarding_request',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
