# Generated by Django 5.2.11 on 2026-03-10 10:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('identity', '0002_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('customer_phone', models.CharField(max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('business_type', models.CharField(blank=True, choices=[('school', 'School'), ('college', 'College'), ('office', 'Office'), ('retailer', 'Retailer'), ('individual', 'Individual')], max_length=20, null=True)),
                ('enquiry_source', models.CharField(choices=[('website', 'Website'), ('mobile_app', 'Mobile App'), ('phone', 'Phone'), ('email', 'Email'), ('walk_in', 'Walk In')], default='website', max_length=20)),
                ('enquiry_status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quotation_sent', 'Quotation Sent'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('preferred_delivery_date', models.DateField(blank=True, null=True)),
                ('budget_range', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('delivery_city', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_state', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('converted_to_quotation_id', models.BigIntegerField(blank=True, null=True)),
                ('converted_to_order_id', models.BigIntegerField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('referrer_url', models.TextField(blank=True, null=True)),
                ('utm_source', models.CharField(blank=True, max_length=100, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=100, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_enquiries', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='identity.user')),
            ],
            options={
                'verbose_name': 'Enquiry',
                'verbose_name_plural': 'Enquiries',
                'db_table': 'enquiry_enquiry',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnquiryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('product_name', models.CharField(blank=True, max_length=500, null=True)),
                ('product_sku', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('quantity', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='enquiry.enquiry')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enquiry_items', to='categories.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiry_items', to='categories.productvariant')),
            ],
            options={
                'verbose_name': 'Enquiry Item',
                'verbose_name_plural': 'Enquiry Items',
                'db_table': 'enquiry_item',
            },
        ),
        migrations.CreateModel(
            name='EnquiryStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('new', 'New'), ('contacted', 'Contacted'), ('quotation_sent', 'Quotation Sent'), ('converted', 'Converted'), ('lost', 'Lost')], max_length=20, null=True)),
                ('to_status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quotation_sent', 'Quotation Sent'), ('converted', 'Converted'), ('lost', 'Lost')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiry_status_changes', to=settings.AUTH_USER_MODEL)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='enquiry.enquiry')),
            ],
            options={
                'verbose_name': 'Enquiry Status History',
                'verbose_name_plural': 'Enquiry Status Histories',
                'db_table': 'enquiry_status_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
