# Generated by Django 5.2.11 on 2026-03-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pdf_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='return_policy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='show_in_store',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.TextField(blank=True, help_text='JSON array of tags', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='track_inventory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='search_keywords',
            field=models.TextField(blank=True, help_text='JSON array of search keywords', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='search_vector',
            field=models.TextField(blank=True, help_text='Search vector placeholder', null=True),
        ),
    ]
